title: MGU SRT
author: Kapdap
email: kapdap@pm.me

product_name: MGU SRT
game_name: "Martian Gothic: Unification"

provider_version: 0.9.0.0
interface_version: 0.9.0.1
directx_version: 0.9.0.0

show_excerpts: true

markdown: kramdown

github_username: kapdap
rss: rss

minima:
  date_format: "%F %I:%M %p"

header_pages:
 - index.md
 - downloads.md
 - screenshots.md
 - changelog.md
 - LICENSE.md
 - about.md

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
