title: MGU SRT
author: Kapdap
email: kapdap@protonmail.com
show_excerpts: false

markdown: kramdown

github_username: kapdap
rss: rss

header_pages:
 - index.md
 - changelog.md
 - LICENSE.md

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
